### ISSUE TITLE
MADNESS dependency

### ISSUE THREAD

**Issue by keceli** [NWChemEx-Project/ParallelZone#97]
Currently, ParallelZone depends on MADNESS, more specifically MADWorld (see [here](https://github.com/NWChemEx-Project/ParallelZone/blob/master/include/parallelzone/runtime/runtime_view.hpp)). In the weekly meeting today, we had a discussion about keeping or removing this dependency and decided to create an issue to follow up. Note that TiledArray (hence TensorWrapper) depends on MADNESS; so the discussion is about having an explicit dependency on MADWorld at the ParallelZone level. 

Somehow relevant past issues: #15 #55

**Comment by wadejong** [comment]
The little piece of C++ code we define related to "thread_local" shows up in ParallelZone, Chemist and TensorWrapper. I commented it out in my build, and it did not run into these warnings. This may have gotten resolved in the latest cppyy version or llvm version. Looking at the email exchanges, it seemed to be a llvm issue.

**Comment by twindus** [comment]
@keceli @wadejong Can we close this issue?

**Comment by keceli** [comment]
Not yet, MADWorld is still required. If there is a consensus to remove it, I can do it.

**Comment by twindus** [comment]
@wadejong and @ryanmrichard Opinions on this?

**Comment by ryanmrichard** [comment]
I vote we drop it from ParallelZone.

**Comment by twindus** [comment]
I agree.  We can bring it back if we really need it.

**Comment by wadejong** [comment]
Agree...it just means we need a mechanism to get an MPI communicator.

**Comment by ryanmrichard** [comment]
I think we can close this issue now, with the caveat that MADNESS is still in the CMakeLists.txt.
